export { SchemaModule, type AjvConfig } from './schema.module.js';
export { SchemaRegistryService } from './schema-registry.service.js';
export { SchemaCompilerService } from './schema-compiler.service.js';
export { SchemaIndexService } from './schema-index.service.js';
export { SchemaCacheService } from './schema-cache.service.js';
export { SchemaDiscoveryService } from './schema-discovery.service.js';
export { SchemaLoaderService } from './schema-loader.service.js';
export { SchemaMetadataService } from './schema-metadata.service.js';
export { SchemaResolverService } from './schema-resolver.service.js';
export { SchemaDependencyGraphService } from './schema-dependency-graph.service.js';
export type { SchemaMeta, SchemaId, SchemaCategory, RegistryConfig, RegistryStats, SchemaIndexEntry, SchemaSearchQuery, DiscoveryResult, CompilationResult, ReferenceInfo } from './types.js';
export { SchemaRegistryError, SchemaNotFoundError, DuplicateSchemaError, InvalidSchemaError, ReferenceResolutionError, CompilationError, CircularDependencyError } from './errors.js';
