# Storynaram Setup Script
# ========================
# Run this script to initialize or reset the Storynaram project structure.
# This script is idempotent — safe to run multiple times.

param(
    [string]$ProjectRoot = (Get-Location).Path,
    [switch]$Force
)

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Storynaram — Project Setup Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Project Root: $ProjectRoot" -ForegroundColor Gray
Write-Host ""

# =====================
# Verify Project Root
# =====================
if (-not (Test-Path $ProjectRoot)) {
    Write-Host "ERROR: Project root does not exist: $ProjectRoot" -ForegroundColor Red
    exit 1
}

# =====================
# Create Directory Structure
# =====================
Write-Host "[1/4] Creating directory structure..." -ForegroundColor Yellow

$directories = @(
    # Foundation
    "config",
    # World
    "world",
    # Timeline
    "timeline",
    # Characters
    "characters",
    # Locations
    "locations",
    # Organizations
    "organizations",
    # Religions
    "religions",
    # Languages
    "languages",
    # Species
    "species",
    # Races
    "races",
    # Magic
    "magic",
    # Technology
    "technology",
    # Items
    "items",
    # Lore
    "lore",
    # Society
    "economy",
    "politics",
    "laws",
    "cultures",
    "education",
    # Narrative
    "books",
    "chapters",
    "scenes",
    "dialogues",
    "plots",
    # Intelligence
    "memory",
    "memory/ai",
    "memory/character",
    "memory/world",
    "memory/timeline",
    "memory/decisions",
    "memory/canon",
    "memory/consistency",
    # Support
    "templates",
    "schemas",
    "prompts",
    "references",
    "research",
    "notes",
    "reviews",
    # Assets
    "assets",
    "assets/maps",
    "assets/images",
    "assets/flags",
    "assets/symbols",
    "assets/diagrams",
    "assets/cover",
    # Operations
    "exports",
    "scripts",
    "scripts/validation",
    "scripts/generators",
    "scripts/import",
    "scripts/export",
    "logs",
    "archive",
    "backups"
)

$created = 0
$skipped = 0

foreach ($dir in $directories) {
    $path = Join-Path $ProjectRoot $dir
    if (-not (Test-Path $path)) {
        New-Item -ItemType Directory -Path $path -Force | Out-Null
        Write-Host "  + Created: $dir" -ForegroundColor Green
        $created++
    } else {
        $skipped++
    }
}

Write-Host "  Directories: $created created, $skipped already exist" -ForegroundColor Gray

# =====================
# Create Config JSON Files
# =====================
Write-Host "[2/4] Creating configuration files..." -ForegroundColor Yellow

$configFiles = @(
    "config/project.json",
    "config/settings.json",
    "config/metadata.json",
    "config/version.json",
    "config/ai_rules.json",
    "config/writing_rules.json",
    "config/naming_rules.json",
    "config/id_rules.json"
)

$cfCreated = 0
$cfSkipped = 0

foreach ($cf in $configFiles) {
    $path = Join-Path $ProjectRoot $cf
    if ((-not (Test-Path $path)) -or $Force) {
        Set-Content -Path $path -Value "{}" -Encoding UTF8 -NoNewline
        if ($Force -and (Test-Path $path)) {
            Write-Host "  ~ Reset: $cf" -ForegroundColor Yellow
        } else {
            Write-Host "  + Created: $cf" -ForegroundColor Green
        }
        $cfCreated++
    } else {
        $cfSkipped++
    }
}

Write-Host "  Config files: $cfCreated created, $cfSkipped already exist" -ForegroundColor Gray

# =====================
# Create README Files
# =====================
Write-Host "[3/4] Skip: README files not regenerated by setup script" -ForegroundColor Yellow
Write-Host "  (Each directory already has a README.md from initial setup)" -ForegroundColor Gray

# =====================
# Create .gitignore if not exists
# =====================
Write-Host "[4/4] Creating .gitignore..." -ForegroundColor Yellow

$gitignorePath = Join-Path $ProjectRoot ".gitignore"
if ((-not (Test-Path $gitignorePath)) -or $Force) {
    $gitignoreContent = @'
# Storynaram .gitignore

# Operating System Files
Thumbs.db
.DS_Store
Desktop.ini
*.swp
*.swo
*~
~$*

# IDE and Editor Files
.idea/
.vscode/
*.sublime-project
*.sublime-workspace
*.code-workspace
.project
.classpath
.settings/
*.iml

# Python
__pycache__/
*.py[cod]
*.pyo
*.egg-info/
dist/
build/
*.egg
.venv/
venv/
env/

# Node
node_modules/
npm-debug.log*
yarn-debug.log*
yarn-error.log*
package-lock.json
yarn.lock

# Logs
*.log

# Secrets and Credentials
*.key
*.pem
*.cert
*.secret
.env
.env.local
.env.*.local
secrets/
credentials/
api_keys/

# Backup and Archive
/backups/
/archive/

# Export Outputs
/exports/*.epub
/exports/*.mobi
/exports/*.pdf
/exports/*.docx

# Large Generated Files
*.generated.*
/tmp/
/temp/

# AI Cache and Temp
.ai_cache/
.ai_temp/
'@
    Set-Content -Path $gitignorePath -Value $gitignoreContent -Encoding UTF8
    Write-Host "  + Created: .gitignore" -ForegroundColor Green
} else {
    Write-Host "  - Skipped: .gitignore (already exists)" -ForegroundColor Gray
}

# =====================
# Summary
# =====================
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Setup Complete!" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Project Root: $ProjectRoot"
Write-Host "Total Directories: $($directories.Count)"
Write-Host "Config Files: $($configFiles.Count)"
Write-Host ""
Write-Host "Next Steps:" -ForegroundColor Yellow
Write-Host "  1. Review ARCHITECTURE.md for system design"
Write-Host "  2. Review PROJECT_GUIDE.md for conventions"
Write-Host "  3. Edit config/ files to define your project"
Write-Host "  4. Start building in world/, characters/, or books/"
Write-Host ""
